#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app
EXPOSE 5000


FROM base AS final
WORKDIR /app
COPY . /app/
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "Miniblog.Core.dll"]